### ISSUE TITLE
ENH: Add shape and dtype to TiffFile

### ISSUE THREAD

**Issue by jakirkham** [blink1073/tifffile#10]
It would be nice to be able to inspect the `shape` and `dtype` before memory mapping or reading the data into memory. It looks like that information can be gathered from `series` perhaps, but maybe I'm misguided.

**Comment by blink1073** [comment]
Hi @jakirkham, this library is a mirror of http://www.lfd.uci.edu/~gohlke/code/tifffile.py.html, I do not intend to add features here.

**Comment by jakirkham** [comment]
Is there some way I should be raising these sorts of things normally?

Ping @cgohlke.

**Comment by cgohlke** [comment]
Better email me directly. 
Tiff files may contain pages/arrays with different dtypes and shapes. Tiff pages with "compatible" dtype and shape are grouped into series. Use the `pages` or `series` attributes to inspect shapes and dtypes of the data in the file.

**Comment by jakirkham** [comment]
Thanks @cgohlke. The information about `series` was what I wasn't understanding before. Thanks for clarifying.
