### ISSUE TITLE
Maintaining/Packaging more of cgohlke's Packages, such as czifile.py ?

### ISSUE THREAD

**Issue by csachs** [blink1073/tifffile#24]
this might be slightly off-topic, but as @blink1073 maintains the tifffile PyPI package of Christoph Gohlke's tifffile.py, I wonder if he'd be willing to maintain more of Christoph Gohlke's Python packages, such as czifile.py ?

Or, maybe @cgohlke could upload his excellent packages to PyPI (and/or host them on github?)?
It's a pity that various old versions float around, without an easy way of keeping up to date with the newest version...

Feel free to close this issue…

**Comment by blink1073** [comment]
Hi @csachs, I am not interested in taking on any other packages.
