### ISSUE TITLE
Raspbian compatible version

### ISSUE THREAD

**Issue by scivision** [blink1073/tifffile#31]
UPDATED:

For Raspberry Pi on Raspbian 9.1 stretch, use the latest Numpy &ge; 1.13 instead of python3-numpy (version 1.12) by:
```sh
apt remove python3-numpy
pip3 install numpy
```

---

This is because tifffile>0.6 requires Numpy 1.13, while the Raspberry Pi has Numpy 1.12 with most up to date Raspbian 9.1 currently available.

Otherwise, the error upon `import tifffile` is

> RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

**Comment by blink1073** [comment]
Hi @scivision, I don't officially support Raspberry Pi, so I think leaving this issue open is a good compromise.

**Comment by scivision** [comment]
Yes tifffile 0.6 was adequate for my needs. In a year or so Raspbian will get updated anyway.

**Comment by scivision** [comment]
Hi @blink1073, I updated my initial comment with a solution. Numpy is now a `.whl` for ARM including Raspberry Pi, so it's very fast to install `pip install numpy`
