### ISSUE TITLE
Version on pip

### ISSUE THREAD

**Issue by Czaki** [blink1073/tifffile#33]
I download tifffile source from pypi (https://pypi.python.org/pypi/tifffile) I see version mismatch. in __init__.py is 0.13.0 but tifffile.py is in version 2017.03.17 (i think 0.12.0). Can you check it and force proper version in pypi?

**Comment by blink1073** [comment]
Fixed, thanks for the heads up!

**Comment by Czaki** [comment]
Why requirements still says python 2.7 or 3.x if Christoph Gohlke do not support python 2.7?

**Comment by blink1073** [comment]
I made a few tweaks to support Python 2.7 as a best effort.

**Comment by Czaki** [comment]
Nice :)
