### ISSUE TITLE
Add option to specify which frame you want in a page?

### ISSUE THREAD

**Issue by HazenBabcock** [blink1073/tifffile#41]
An option so that you can specify which frame you want in a page would be useful. Some .tif files can have thousands of frames on a single page and it would be great if you could load just one of the frames, instead of having to load the entire page and then slice.

**Comment by cgohlke** [comment]
Do you have an example of such a file? Usually TIFF files do not have too many *planes* in one page. If you are referring to *frames* in truncated ImageJ hyperstacks, you should be able to memory map the stack for efficient access. If you are referring to image *tiles* such as in geotiff or microscopy slides, that is on the todo list.

**Comment by HazenBabcock** [comment]
The file I have was created by importing a Nikon ND2 file into ImageJ using bioformats. When I saved it as a TIFF file using ImageJ it had 1 page, 10k planes(?) per page. I cut it down to 500 planes and uploaded it [here](https://drive.google.com/open?id=1UjegfhMrtx8mHvmT_TKWUKAB3ENKHrys).

`tifffile.TiffFile(filename).asarray(key=0).shape` returns [500, 256, 256].

**Comment by cgohlke** [comment]
You seem to be using an older version of tifffile, which optimizes ImageJ hyperstack access by falsely reporting the shape of the image contained in the first page. That has been fixed. For more efficient access you can directly read or memory map the ImageJ hyperstack instead of indexing TIFF pages.

**Comment by HazenBabcock** [comment]
Yes, that looks like the problem. I updated to v0.14.0 and now it reports 1 plane/page and 500 pages and initial loading is a lot faster. Apologies for the noise, for some reason I thought I already had the latest version.
