### ISSUE TITLE
Resolution unit question

### ISSUE THREAD

**Issue by sebi06** [blink1073/tifffile#48]
Hi,

i saw:

```
Save a volume with xyz voxel size 2.6755x2.6755x3.9474 µm^3 to ImageJ file:

>>> volume = numpy.random.randn(57*256*256).astype('float32')
>>> volume.shape = 1, 57, 1, 256, 256, 1  # dimensions in TZCYXS order
>>> imsave('temp.tif', volume, imagej=True, resolution=(0.373759, 0.373759),
...        metadata={'spacing': 3.947368, 'unit': 'um'})
```

and I am wondering who this conversion works or more precis why is 2.6755 micron = 0.373759 ???.

I hope this question is not to silly, but I just cannot wrap my head around it ...

**Comment by cgohlke** [comment]
The x and y resolution values are stored in dedicated TIFF tags, not the ImageJ description. Resolution in TIFF is defined as "number of pixels per resolution unit". For a pixel size of 2.6755, the number of pixels that fit it in one micron is `1.0/2.6755≈0.373759`.

**Comment by sebi06** [comment]
Thx. I missed that point
