### ISSUE TITLE
imread returns only one image in certain folders

### ISSUE THREAD

**Issue by ilorevilo** [blink1073/tifffile#53]
When I try to read all tifs in a folder named "2018_11_12-L2" I get an array with just one image:
```
inputfolder = "2018_11_12-L2\\test"
inputfolder = os.path.join(inputfolder, "*.tif")
tiflist = glob.glob(inputfolder)
imagestack= tifffile.imread(tiflist)
print(imagestack.shape)
```
returns (1, 2048, 2048).
Using a different folder name like "2018_11_12" returns the correct array (3, 2048, 2048).
Is this happening because a specific pattern is extracted from the folder name and is there an option to turn this off?

**Comment by cgohlke** [comment]
Try `imread(tiflist, pattern='')`

**Comment by ilorevilo** [comment]
great, that resolved the issue!
