### ISSUE TITLE
packbits compression error

### ISSUE THREAD

**Issue by mluerig** [blink1073/tifffile#61]
It appears that there is an issue with the packbits compression algorithm. This was on Python 3.7, Win10, with tifffile=='2021.7.2' and imagecodecs=='2021.6.8'

```
tiff.imwrite(filepath_save, imstack, compress='packbits')
Traceback (most recent call last):

  File "<ipython-input-5-8cbd07d2b7b3>", line 1, in <module>
    tiff.imwrite(filepath_save, imstack, compress='packbits')

  File "C:\Anaconda3\envs\workspace\lib\site-packages\tifffile\tifffile.py", line 891, in imwrite
    result = tif.write(data, shape, dtype, **kwargs)

  File "C:\Anaconda3\envs\workspace\lib\site-packages\tifffile\tifffile.py", line 2595, in write
    strip = compress(strip)

  File "imagecodecs\_imcd.pyx", line 645, in imagecodecs._imcd.packbits_encode

ValueError: data is not a byte array
```

**Comment by cgohlke** [comment]
Please report issues at https://github.com/cgohlke/tifffile. Anyway, I could not reproduce this yet. What type, dtype, and shape is `imstack`?

**Comment by mluerig** [comment]
```
type(imstack)
Out[17]: numpy.ndarray

imstack.shape
Out[18]: (519, 348, 185)

imstack.dtype
Out[19]: dtype('int16')
```
== > [imstack.zip](https://github.com/blink1073/tifffile/files/6894057/imstack.zip)

this is what I tried to do:

    imstack = tiff.imread("imstack.tif")
    imstack[imstack > 0] = 1
    tiff.imwrite("imstack1.tif", imstack)

**Comment by cgohlke** [comment]
PackBits is a byte oriented algorithm and the current implementation does not allow for dtypes with more than one byte. It usually does not make much sense to compress 16 bit images with PackBits. In cases like this, where most values are zero, the algorithm should perform OK. I'll consider supporting this case in a future version. On the other hand, deflate compression (`compression='zlib'`) is much superior to PackBits.

**Comment by mluerig** [comment]
ok thanks. I only wanted to use packbits because this was the compression in the original file (binary label coming out of 3Dslicer). so, it's a 3D bit array, not sure what the best way to store is. memory and speed wise. in any case, deflate compression is dead-efficient, and I chose it

**Comment by cgohlke** [comment]
This should work with v2021.7.30.

**Comment by mluerig** [comment]
confirmed - thanks!
