### ISSUE TITLE
Relationship to upstream

### ISSUE THREAD

**Issue by tdsmith** [blink1073/tifffile#9]
I'm thrilled to see this in git and on PyPI. What's the relationship of this repository to Christoph Gohlke's releases? What happens to PRs against this repo?

**Comment by blink1073** [comment]
Hi @tdsmith, I am merely acting as a maintainer.  We needed this library for `scikit-image`, so I put it up here and on PyPI.  I consider this to be a snapshot of Christoph's current work.

**Comment by tdsmith** [comment]
Okay, thanks!
